name: auto-build

on:
  push:
    branches:
      - "*"

permissions:
  contents: write

env:
  TZ: Asia/Kolkata

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Pull Arch Linux Docker image
        run: docker pull archlinux:latest

      - name: Clone the repo and Building package
        run: |
           git clone https://"alex5402":"${{ secrets.GITHUBTOKEN }}"@github.com/alex5402/android-studio-alex build
           cd build
           wget https://developer.android.com/studio -O studio.html
           bash update.sh

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG_NAME }}
          release_name: ${{ env.TAG_NAME }}
          body: Workflow Hash ```${{ github.sha }}```
          files: |
            *.pkg.tar.zst
